### ISSUE TITLE
Can you please post a link in the readme to where we can see/use a runing version of this.

### ISSUE THREAD

**Issue by Tritium-VLK** [Michael-Neuman/bitcoin-yield-tracker#1]
It looks lie you have pages setup, can you provide a link?

**Comment by Michael-Neuman** [comment]
Thanks for the suggestion.  I've updated the readme file to include a link to CodeSandbox to preview this project.

https://codesandbox.io/s/github/Michael-Neuman/bitcoin-yield-tracker
